#ifndef CARIBOU_HAL_H
#define CARIBOU_HAL_H

#include <cstdint>
#include <map>
#include <string>
#include <tuple>
#include <typeinfo>
#include <vector>

#include "utils/constants.hpp"
#include "utils/exceptions.hpp"
#include "utils/log.hpp"
#include "utils/utils.hpp"

#include "interfaces/Interface.hpp"
#include "interfaces/InterfaceManager.hpp"

#include "interfaces/I2C/i2c.hpp"
#include "interfaces/Memory/memory.hpp"

#include "Si5345-RevB-CLKOFF-Registers.h"

namespace caribou {

  class caribouHAL {
  public:
    /** Default constructor for creating a new HAL instance
     */
    caribouHAL() = default;

    /** Default destructor
     */
    ~caribouHAL();

    /** Read and return the device identifier from the firmware
     */
    virtual uint8_t getBoardID() = 0;

    /** Read and return the hardware revision
     */
    virtual uint8_t getBoardRev() = 0;

    /** Read byte from onboard memory
     */
    virtual uint8_t readEEPROM(uint16_t) = 0;

    /** Write byte to onboard memory
     */
    virtual void writeEEPROM(uint16_t, int) = 0;

    /** Return human-readable string of firmware version and build timestamp
     */
    virtual std::string getFirmwareVersion() = 0;

    /** Read value from a firmware register
     *
     *  @param address : address of the register to be read
     */
    virtual uintptr_t getFirmwareRegister(uint16_t address) = 0;

    void writeMemory(memory_map mem, size_t offset, uintptr_t value);
    void writeMemory(memory_map mem, uintptr_t value);
    uintptr_t readMemory(memory_map mem, size_t offset);
    uintptr_t readMemory(memory_map mem);
    void streamMemoryToFile(memory_map mem, const size_t offset, const unsigned int N, const std::string& filename);

    /** Read the temperature from the TMP101 device
     *
     *  Returns temperature in degree Celsius with a precision of 0.0625degC
     */
    virtual double readTemperature() = 0;

    /** Set bias voltage
     *
     *  The input parameter should be provided in SI Volts.
     *  The function sets the proper voltage in the DAC corresponding to the selected bias.
     *  The output of the DAC is not enabled.
     */
    virtual void setBiasRegulator(const BIAS_REGULATOR_T regulator, const double voltage) = 0;

    /** Enable/disable the voltage regulator
     *
     *  Enables or disables the output of the coresponding DAC.
     */
    virtual void powerBiasRegulator(const BIAS_REGULATOR_T regulator, const bool enable) = 0;

    /** Set output voltage of a voltage regulator
     *
     *  The input parameter should be provided in SI Volts and Amps.
     *  The function sets the proper reference voltage (PWR_ADJ_*) in a DAC
     *  corresponding to the regulator. It also configures the corresponding current/power monitor.
     *  The output of the DAC is not enabled.
     */
    virtual void
    setVoltageRegulator(const VOLTAGE_REGULATOR_T regulator, const double voltage, const double maxExpectedCurrent) = 0;

    /** Set the current source.
     * ~current~ is provided in uA.
     */
    virtual void setCurrentSource(const CURRENT_SOURCE_T source,
                                  const unsigned int current,
                                  const CURRENT_SOURCE_POLARITY_T polarity) = 0;

    /** Enable/disable the voltage regulator
     *
     *  If enable is true, the function enables first output
     *  of the coresponding DAC (PWR_ADJ_*). Afterwards, PWER_EN_* is asserted.
     *  If enable is false, the sequence is performed in the opposite direction.
     */
    virtual void powerVoltageRegulator(const VOLTAGE_REGULATOR_T regulator, const bool enable) = 0;

    /** Enables current source
     */
    virtual void powerCurrentSource(const CURRENT_SOURCE_T source, const bool enable) = 0;

    // The method disables all outputs of SI5345 jitter attenuator/clock multiplier using a table generated by
    // ClockBuilderPro
    virtual void disableSI5345() = 0;

    // The method sets SI5345 jitter attenuator/clock multiplier using a table generated by ClockBuilderPro
    virtual void configureSI5345(SI5345_REG_T const* const regs, const size_t length) = 0;

    // The method return true when SI5345 jitter attenuator/clock multiplier is locked
    virtual bool isLockedSI5345() = 0;

    // The method sets pulse parameters for an onboard pulser
    virtual void configurePulseParameters(const unsigned channel_mask,
                                          const uint32_t periods,
                                          const uint32_t time_active,
                                          const uint32_t time_idle,
                                          const double voltage) = 0;

    // The method configures the onboard pulser
    virtual void
    configurePulser(unsigned channel_mask, const bool ext_trigger, const bool ext_trig_edge, const bool idle_state) = 0;

    // The method starts the onboard pulser
    virtual void startPulser(unsigned channel_mask) = 0;

    // The method enables the onboard pulser
    virtual void enablePulser(unsigned channel_mask) = 0;

    // The method disables (stops) the onboard pulser
    virtual void disablePulser(unsigned channel_mask) = 0;

    // The method returns 4 status bits corresponding to 4 pulser channels if a channel is running
    virtual uint32_t getPulserRunning() = 0;

    // The returns the number of pulses that were done since a pulser channel was started for the specified channel.
    virtual uint32_t getPulseCount(const uint32_t channel) = 0;

    // The method measures current
    // It return value in SI A.
    virtual double measureCurrent(const VOLTAGE_REGULATOR_T regulator) = 0;

    // The method measures power
    // It return value in SI W.
    virtual double measurePower(const VOLTAGE_REGULATOR_T regulator) = 0;

    // The method measures voltage
    // It returns value in SI V.
    virtual double measureVoltage(const VOLTAGE_REGULATOR_T regulator) = 0;

    // The method measures voltage
    // It returns value in SI V.
    virtual double readBias(const BIAS_REGULATOR_T regulator) = 0;

    virtual double readSlowADC(const SLOW_ADC_CHANNEL_T channel) = 0;

    virtual void monitorAlert() = 0;

    /* return status of a specific channel of the Alert monitor
     */
    virtual bool getAlertStatus(const GPIO_T IOCHANNEL) = 0;

    /** Set CMOS Input levels
     */
    virtual void setInputCMOSLevel(double voltage) = 0;

    /** Set CMOS Output levels
     */
    virtual void setOutputCMOSLevel(double voltage) = 0;

    // It's not possible to power on/off DCDC converter by software
    virtual void setDCDCConverter(const DCDC_CONVERTER_T converter, const double voltage) = 0;

    // Enable DC/DC converter
    virtual void powerDCDCConverter(const DCDC_CONVERTER_T converter, const bool enable) = 0;

  protected:
    /** Initailization of the board
     */
    virtual void Initialize();

    /** Finalization of the board
     */
    virtual void Finalize();

    /** Set current/power monitor
     */
    virtual void setCurrentMonitor(const uint8_t device, const double maxExpectedCurrent, bool enableLimit) = 0;

    /** General reset of the board
     */
    virtual void generalReset();

  private:
    // General reset of the board done
    static bool generalResetDone;
  }; // class caribouHAL

} // namespace caribou

#endif /* CARIBOU_HAL_H */
