/** CaR board I2C device mapping and addresses
 */

#ifndef CARIBOU_CARBOARD_H
#define CARIBOU_CARBOARD_H

#include "CarboardConstants.hpp"
#include "hardware_abstraction/HAL.hpp"

namespace caribou {
  namespace carboard {
    class Carboard : public caribouHAL {

    public:
      /** Default constructor for creating a new HAL instance
       */
      Carboard();

      /** Default destructor
       */
      virtual ~Carboard() = default;

      /** Read and return the device identifier from the firmware
       */
      uint8_t getBoardID() override;

      /** Read and return the hardware revision
       */
      uint8_t getBoardRev() override;

      /** Read byte from onboard memory
       */
      uint8_t readEEPROM(uint16_t addr) override;

      /** Write byte to onboard memory
       */
      void writeEEPROM(uint16_t addr, int val) override;

      /** Return human-readable string of firmware version and build timestamp
       */
      std::string getFirmwareVersion() override;

      /** Read value from a firmware register
       *
       *  @param address : address of the register to be read
       */
      uintptr_t getFirmwareRegister(uint16_t address) override;

      /** Read the temperature from the TMP101 device
       *
       *  Returns temperature in degree Celsius with a precision of 0.0625degC
       */
      double readTemperature() override;

      /** Set bias voltage
       *
       *  The input parameter should be provided in SI Volts.
       *  The function sets the proper voltage in the DAC corresponding to the selected bias.
       *  The output of the DAC is not enabled.
       */
      void setBiasRegulator(const BIAS_REGULATOR_T regulator, const double voltage) override;

      /** Enable/disable the voltage regulator
       *
       *  Enables or disables the output of the coresponding DAC.
       */
      void powerBiasRegulator(const BIAS_REGULATOR_T regulator, const bool enable) override;

      /** Set output voltage of a voltage regulator
       *
       *  The input parameter should be provided in SI Volts and Amps.
       *  The function sets the proper reference voltage (PWR_ADJ_*) in a DAC
       *  corresponding to the regulator. It also configures the corresponding current/power monitor.
       *  The output of the DAC is not enabled.
       */
      void setVoltageRegulator(const VOLTAGE_REGULATOR_T regulator,
                               const double voltage,
                               const double maxExpectedCurrent) override;

      /** Set the current source.
       * ~current~ is provided in uA.
       */
      void setCurrentSource(const CURRENT_SOURCE_T source,
                            const unsigned int current,
                            const CURRENT_SOURCE_POLARITY_T polarity) override;

      /** Enable/disable the voltage regulator
       *
       *  If enable is true, the function enables first output
       *  of the coresponding DAC (PWR_ADJ_*). Afterwards, PWER_EN_* is asserted.
       *  If enable is false, the sequence is performed in the opposite direction.
       */
      void powerVoltageRegulator(const VOLTAGE_REGULATOR_T regulator, const bool enable) override;

      /** Enables current source
       */
      void powerCurrentSource(const CURRENT_SOURCE_T source, const bool enable) override;

      // The method disables all outputs of SI5345 jitter attenuator/clock
      // multiplier using a table generated by ClockBuilderPro
      void disableSI5345() override;

      // The method sets SI5345 jitter attenuator/clock multiplier using a table
      // generated by ClockBuilderPro
      void configureSI5345(SI5345_REG_T const* const regs, const size_t length) override;

      // The method reads a whole page (32 byte) from the SI5315
      iface_i2c::dataVector_type readSI5345(int page);

      // The method return true when SI5345 jitter attenuator/clock multiplier is
      // locked
      bool isLockedSI5345() override;

      // Sets frequency of Si570 USRCLK on ZC706
      void setUSRCLK(const uint64_t freq);

      // The method sets pulse parameters for an onboard pulser
      void configurePulseParameters(const unsigned channel_mask,
                                    const uint32_t periods,
                                    const uint32_t time_active,
                                    const uint32_t time_idle,
                                    const double voltage) override;

      // The method configures the onboard pulser
      void configurePulser(unsigned channel_mask,
                           const bool ext_trigger,
                           const bool ext_trig_edge,
                           const bool idle_state) override;

      // The method starts the onboard pulser
      void startPulser(unsigned channel_mask) override;

      // The method enables the onboard pulser
      void enablePulser(unsigned channel_mask) override;

      // The method disables (stops) the onboard pulser
      void disablePulser(unsigned channel_mask) override;

      // The method returns 4 status bits corresponding to 4 pulser channels if a channel is running
      uint32_t getPulserRunning() override;

      // The returns the number of pulses that were done since a pulser channel was started for the specified channel.
      uint32_t getPulseCount(const uint32_t channel) override;

      // The method measures current
      // It return value in SI A.
      double measureCurrent(const VOLTAGE_REGULATOR_T regulator) override;

      // The method measures power
      // It return value in SI W.
      double measurePower(const VOLTAGE_REGULATOR_T regulator) override;

      // The method measures voltage
      // It returns value in SI V.
      double measureVoltage(const VOLTAGE_REGULATOR_T regulator) override;

      // The method measures voltage
      // It returns value in SI V.
      double readBias(const BIAS_REGULATOR_T regulator) override;

      double readSlowADC(const SLOW_ADC_CHANNEL_T channel) override;

      void setDCDCConverter(const DCDC_CONVERTER_T converter, const double voltage) override;

      void powerDCDCConverter(const DCDC_CONVERTER_T converter, const bool enable) override;

      /** print status of power monitor and SI5345 lock
       */
      void monitorAlert() override;

      /* return status of a specific channel of the Alert monitor
       */
      bool getAlertStatus(const GPIO_T IOCHANNEL) override;

      /** Set CMOS Input levels
       */
      void setInputCMOSLevel(double voltage) override;

      /** Set CMOS Output levels
       */
      void setOutputCMOSLevel(double voltage) override;

    private:
      void generalReset() override;

      // Access to FPGA memory mapped registers
      memory_map firmware_mem{CARIBOU_CONTROL_BASE_ADDRESS, CARIBOU_CONTROL_MAP_SIZE, PROT_READ};
      memory_map pulser{CARIBOU_PULSER_BASE_ADDRESS, CARIBOU_PULSER_MAP_SIZE, PROT_READ | PROT_WRITE};

      /** Set output voltage on a DAC7678 voltage regulator
       *
       *  The input parameter should be provided in SI Volts
       */
      void setDACVoltage(const uint8_t device, const uint8_t address, const double voltage);

      /** Read configured output voltage register form DAC7678
       *
       * Returns the configured voltage in SI Volts
       */
      double getDACVoltage(const uint8_t device, const uint8_t address);


      /** Power up/down selected output voltage on a DAC7678 voltage regulator
       */
      void powerDAC(const bool enable, const uint8_t device, const uint8_t address);

      /** Set current/power monitor
       */
      void setCurrentMonitor(const uint8_t device, const double maxExpectedCurrent, bool enableLimit) override;

    }; // class Carboard
  }    // namespace carboard
} // namespace caribou

#endif /* CARIBOU_CARBOARD_H */
