#ifndef DSIPM_FRAMEDECODER_HPP
#define DSIPM_FRAMEDECODER_HPP

#include <vector>

#include "utils/datatypes.hpp"
#include "utils/log.hpp"
#include "utils/utils.hpp"

#include "dSiPMDefaults.hpp"
#include "dSiPMPixels.hpp"

#include <fstream>

// for pixel mapping
#define DSIPM_N_QUADCOL 16                   // columns per quadrant
#define DSIPM_N_QUADROW 16                   // rows per quadrant
#define DSIPM_N_COL 2 * DSIPM_N_QUADCOL      //   32 -- all columns
#define DSIPM_N_ROW 2 * DSIPM_N_QUADROW      //   32 -- all rows
#define DSIPM_N_PIX DSIPM_N_COL* DSIPM_N_ROW // 1024 -- all pixels

// data structure in memory
#define DSIPM_N_HITDATA 32 // blocks of hit data
#define DSIPM_N_TIMEDATA 7 // blocks of time stamp data
#define DSIPM_N_DAQDATA 2  // blocks of DAQ data generated by FPGA

namespace caribou {

  class dSiPMFrameDecoder {
  public:
    dSiPMFrameDecoder() { generateMapping(); };

    /* Function to convert the input data stream into pixel data.
     */
    template <typename T>
    pearydata decodeFrame(const std::vector<T>& rawFrame, bool suppressZero = false, bool read2bit = false);

    // Additional frame data from the FPGA
    struct fpgadata {
      bool second_2bit;          // true in the second frame if 2-bit mode is used
      uint8_t timestamp_check;   // for debugging purposes
      uint64_t timestamp_coarse; // coarse timestamp of the trigger (3 MHz)
      uint8_t timestamp_fine;    // fine timestamp of the trigger (408 MHz)
      uint32_t trigger_id;       // trigger ID
    };

    /* Method to decode the FPGA trailer to the frame and return the information
     * @param rawFrame raw data frame read fro the FPGA buffer
     * @return Tuple with: Control timestamp, readout timestamp, trigger ID
     */
    template <typename T> fpgadata decodeTrailer(const std::vector<T>& rawFrame, bool second = false);

    /* Print zero-suppressed frame to ascii for easy inspection
     */
    void printFrame(const pearydata& frame, const char* filename, bool PrintEndFrame = false);
    /* Print zero-suppressed frame to ascii for easy inspection, using raw input
     * and printing also FPGA time info.
     */
    void printFrame(const pearyRawData& rawFrame, const char* filename, bool PrintEndFrame = false, bool read2bit = false);

    typedef unsigned int index_type;

  private:
    /* Funktions to generate lookup tables.
     * These map between the pixels indices in the raw data stream and
     * the pixel column and row indices in the full matrix.
     */
    void generateMapping();

    /* Get the pixel index inside a quadrant from the index in the raw data stream
     * Suppose the data comes in an array of 1024 entries, like Q1, Q2, Q3, Q4, respectively.
     */
    index_type getIpix(index_type itot);

    /* Get the quadrant a pixel belongs to from the index in the raw data stream
     * Suppose the data comes in an array of 1024 entries, like Q1, Q2, Q3, Q4, respectively.
     */
    index_type getQuad(index_type itot);

    /* Map the pixel index in a quadrant to column and row indices in a quadrant.
     */
    index_type getQuadCol(index_type ipix);
    index_type getQuadRow(index_type ipix);

    /* Map the column and row indices within a quadrant to their global correspondance.
     */
    index_type getCol(index_type ipix, index_type quad);
    index_type getRow(index_type ipix, index_type quad);

    /* For 2bit mode we the data for one quadrant is split in two frames, where
     * the first frame contains the outer half (col 0-7 and 23-31) of the pixels.
     * Thus we need to remap the indices in order to make use of the functions
     * defined above.
     */
    index_type getRemap2bit(index_type ipix);

    /* Lookup tables
     */
    index_type m_indexToCol[1024];
    index_type m_indexToRow[1024];
    index_type m_indexToQuad[1024];
    index_type m_remap2bit[1024];

    /* Print some frames for easy assesment
     */
    std::ofstream m_outfileFrames;
  };

  template <typename T>
  dSiPMFrameDecoder::fpgadata dSiPMFrameDecoder::decodeTrailer(const std::vector<T>& rawFrame, bool second) {

    // Decoding time info from FPGA
    /*
    frame_word[38][31:12] = chip_timestamp_data[211:192]
    frame_word[38][11]    = fpga_second_2bit
    frame_word[38][10:8]  = fpga_timestamp_check[2:0]
    frame_word[38][7:0]   = fpga_timestamp_fine[7:0]
    frame_word[39][31:0]  = fpga_timestamp_coarse[31:0]
    frame_word[40][31:24] = fpga_timestamp_coarse[39:32]
    frame_word[40][23:0]  = fpga_trigger_id[23:0]
    */
    // get the right data words
    index_type fpgaDataFrom = DSIPM_N_HITDATA + DSIPM_N_TIMEDATA;
    // In 2-bit mode we have this info once for each frame.
    // We may want to read from the second.
    if(second)
      fpgaDataFrom = 2 * DSIPM_N_HITDATA + 2 * DSIPM_N_TIMEDATA + 1 * DSIPM_N_DAQDATA;

    auto td1_fpga = static_cast<uint32_t>(rawFrame.at(fpgaDataFrom - 1));
    auto td2_fpga = static_cast<uint32_t>(rawFrame.at(fpgaDataFrom));
    auto td3_fpga = static_cast<uint32_t>(rawFrame.at(fpgaDataFrom + 1));

    // get time info from data words
    fpgadata data;
    data.second_2bit = (td1_fpga & 0x800) != 0;
    data.timestamp_check = (td1_fpga & 0x700) >> 8;
    data.timestamp_fine = (td1_fpga & 0xFF);
    data.timestamp_coarse = static_cast<uint64_t>(td2_fpga) | (static_cast<uint64_t>(td3_fpga & 0xFF000000) << 8);
    data.trigger_id = (td3_fpga & 0xFFFFFF);

    return data;
  }

  template <typename T>
  pearydata dSiPMFrameDecoder::decodeFrame(const std::vector<T>& rawFrame, bool suppressZero, bool read2bit) {
    pearydata data;

    // raw frame is longer if we are in two bit mode
    unsigned int read_n_times = 1;
    if(read2bit) {
      read_n_times = 2;
    }

    // frame complete?
    if(!(rawFrame.size() == (read_n_times * (DSIPM_N_HITDATA + DSIPM_N_TIMEDATA + DSIPM_N_DAQDATA)))) {
      LOG(ERROR) << "decodeFrame: Unexpected frame size " << rawFrame.size() << " expecting "
                 << (read_n_times * (DSIPM_N_HITDATA + DSIPM_N_TIMEDATA + DSIPM_N_DAQDATA));
      return data;
    }

    // Decoding time data from chip
    // we have Bunch Counter (BC), Valid Bit (VB), Fine/ Coarse Time (FT/CT), each for each quadrant.
    uint64_t BC[4] = {0};
    uint8_t FT[4] = {0};
    uint8_t CT[4] = {0};
    bool VB[4] = {0};

    // time data has some eight-fold symmetry... use eight containers for decoding
    const size_t sym = 8;
    uint64_t timeParts[sym] = {0};

    // unwrap time data
    index_type i = 0;
    index_type i_remaped = 0;
    index_type shift = 0;
    for(index_type iwrd = DSIPM_N_HITDATA; iwrd < DSIPM_N_HITDATA + DSIPM_N_TIMEDATA; iwrd++) {

      // get word
      auto word = static_cast<uint32_t>(rawFrame.at(iwrd));

      // iterate through word
      uint32_t bitmask = 0x80000000; // = 1000...000
      for(index_type ibit = 0; ibit < DSIPM_WORD_SIZE; ibit++) {

        // get bits from word
        bool bit_value = (bitmask & word) != 0;
        bitmask = bitmask >> 1; // update AFTER using!

        // append bit to container
        timeParts[i % sym] = timeParts[i % sym] << 1;
        timeParts[i % sym] = timeParts[i % sym] | bit_value;

        i++;
      } // word

    } // timestamp data

    // now we can cherry pick the time info from the 8 containers...
    // why do I feel stupid about telling C++ how many quadrants there are?
    for(index_type iquad = 0; iquad < 4; iquad++) {
      // errase trailing bit, make space for 13 more bits (12-0).
      BC[iquad] = (timeParts[iquad] >> 1) << 13;
      // errase trailing FT, CT and 00, get rid of heading valid bit, then add
      BC[iquad] += (timeParts[iquad + 4] >> 14) & 0x1FFF;
      // again, shift to errase trailing, & to errase heading part
      FT[iquad] = (timeParts[iquad + 4] >> 9) & 0x1F;
      CT[iquad] = (timeParts[iquad + 4] >> 2) & 0x7F;
      VB[iquad] = (timeParts[iquad + 4] >> 27) & 0x1;
    }

    // unwrap hit data:
    // this is tricksy, because we have two cases:
    // 1-bit mode: data comes as discussed in the chip manual: Q0, Q1, Q2, Q3
    //             one word contains the hits of two quadrant columns = 32 pix.
    // 2-bit mode: data for each quadrant is distributed over two frames
    //             one word contains the hits of one quadrant column.
    //             the first half beeing msb's the second half lsb's.
    // in each case i needs to run from 0 to 255.
    // shift needs to run from 0 to 31 in 1-bit mode,
    // shift needs to run from 0 to 15 in 2-bit mode.
    i = 0;
    for(index_type iframe = 0; iframe < read_n_times; iframe++) {
      index_type iwrd_start = iframe * (DSIPM_N_HITDATA + DSIPM_N_TIMEDATA + DSIPM_N_DAQDATA);
      for(index_type iwrd = iwrd_start; iwrd < iwrd_start + DSIPM_N_HITDATA; iwrd++) {

        // get word
        auto word = static_cast<uint32_t>(rawFrame.at(iwrd));

        // iterate through words
        shift = 0;
        for(index_type ibit = 0; ibit < DSIPM_WORD_SIZE / read_n_times; ibit++) {

          // get bits from word
          uint32_t bitmask1 = 0x80000000; // = 1000...000
          uint32_t bitmask2 = 0x00008000; // = 1000...000
          uint32_t value = (bitmask1 >> shift) & word ? 1 : 0;
          // if we are in 2-bit mode the second half of the word belongs to the same pixel
          if(read2bit) {
            uint32_t value2 = (bitmask2 >> shift) & word ? 1 : 0;
            value = (value << 1) | value2;
          }

          // check indices:
          LOG(TRACE) << "Indices:"
                     << "  i " << i << "  iframe " << iframe << "  iwrd " << iwrd << "  ibit " << ibit << "  shift " << shift
                     << "  \n";

          if(value != 0) {
            LOG(TRACE) << "Word1 " << std::hex << word << " gives " << (uint32_t((bitmask1 >> shift) & word) ? 1 : 0);
            LOG(TRACE) << "Word2 " << std::hex << word << " gives " << (uint32_t((bitmask2 >> shift) & word) ? 1 : 0);
            LOG(TRACE) << "using shift " << std::hex << shift << " Combined: " << value;
          }

          // for 2-bit mode we need to remap i
          if(read2bit)
            i_remaped = m_remap2bit[i];
          else
            i_remaped = i;

          // derive column and row from index
          index_type col = m_indexToCol[i_remaped];
          index_type row = m_indexToRow[i_remaped];
          index_type quad = m_indexToQuad[i_remaped];

          // Increment for next pixel
          shift++;
          i++;

          // Suppress empty pixels, if we wish to do so.
          if(suppressZero == true && value == 0) {
            continue;
          }

          // std::cout << "PEARY dSiPM FrameDecoder: col, row " << col << " " << row << std::endl;
          // LOG(ERROR) << "PEARY dSiPM FrameDecoder: col, row " << col << " " << row << std::endl;

          // If we have data, the valid bit should be set for this quadrant
          if(value != 0 && VB[quad] == 0) {
            LOG(WARNING) << "we have hit data, although the valid bit is false, col row quad " << col << " " << row << " "
                         << quad;
            // return pearydata(); // for debugging i still need to see something...
          }

          // Fill data structure.
          data[std::make_pair(col, row)] =
            std::make_unique<dsipm_pixel>(static_cast<uint8_t>(value), VB[quad], BC[quad], FT[quad], CT[quad]);

        } // bits

      } // words

    } // frames

    return data;
  }

} // namespace caribou

#endif
